version: '3.4'
services:
    webserver:
      image: airflow_mm:1.0
      restart: always
      command: webserver
      ports:
        - "8080:8080"
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@db/airflow
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__BASE_LOG_FOLDER=/logs
        - AIRFLOW__CORE__FERNET_KEY="7y3v6WymWIdCfWw3qneXCBbbFRSSLI35jfGe7cyQNhs="
      volumes:
        - "./logs:/logs"
      depends_on:
        - "db"

    scheduler:
      image: airflow_mm:1.0
      restart: always
      command: scheduler
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@db/airflow
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__BASE_LOG_FOLDER=/logs
        - AIRFLOW__CORE__FERNET_KEY="7y3v6WymWIdCfWw3qneXCBbbFRSSLI35jfGe7cyQNhs="
      volumes:
        - "./logs:/logs"
      depends_on:
        - "db"