apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-web
    spec:
      containers:
      - name: airflow-web
        image: airflow_mm:1.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "500m"
            memory: "300Mi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: airflow-env

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: airflow-web
  name: airflow-web
  namespace: airflow
spec:
  ports:
  - name: airflow-web
    port: 8090
    protocol: TCP
    targetPort: 8080
  selector:
    app: airflow-web
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: airflow_mm:1.0
        args: ["scheduler"]
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "500m"
            memory: "300Mi"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        envFrom:
        - configMapRef:
            name: airflow-env

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
  labels:
    app: airflow-env
data:
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://admin:admin@postgresql/airflow"
  AIRFLOW__CORE__STORE_SERIALIZED_DAGS: "true"
  AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: "30"
  AIRFLOW__CORE__STORE_DAG_CODE: "true"
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "true"
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "true"
  AIRFLOW__KUBERNETES__IN_CLUSTER: "true"
  AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "Never"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "airflow_mm"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.0"
  AIRFLOW__CORE__FERNET_KEY: "7y3v6WymWIdCfWw3qneXCBbbFRSSLI35jfGe7cyQNhs="
  